routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

//
// Route::prefix('volunteer')->group(function () {
//     //Route::resource('options', 'ProyectosController');
//
//
// });

Route::resources([
	'activities' => 'ActivitiesController',
	'communities' => 'CommunitiesController',
	'volunteers' => 'VolunteersController'
]);

Route::get('activities/{id}/destroy', [
			'uses' => 'ActivitiesController@destroy',
			'as'   => 'activities.destroy'

]);

Route::get('communities/{id}/destroy', [
			'uses' => 'CommunitiesController@destroy',
			'as'   => 'communities.destroy'

]);

Route::get('volunteers/{id}/destroy', [
			'uses' => 'VolunteersController@destroy',
			'as'   => 'volunteers.destroy'

]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Activity.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{
  //

  protected $table = "activities";
  protected $guarded = [];


  public function communities()
  {
  return $this->belongsToMany('App\Community', 'activities_communities', 'activities_id', 'communities_id')
							->withPivot('status_id')->withTimestamps();;
	}

	public function volunteers()
	{
	return $this->hasMany('App\Volunteer', 'activity');
	}

}

app/Http/Controllers/ActivitiesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ActivitiesRequest;
use App\Activity;
use App\Community;
use Faker\Factory as Faker;

class ActivitiesController extends Controller
{
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
			$this->middleware('auth');
	}
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
      /*
      FACILITA LA OBSERVACION DE LOS CAMPOS CREADOS POR FAKER
      $faker = Faker::create();
      echo $faker->name;
      echo $faker->company;
      echo $faker->sentence($nbWords = 6, $variableNbWords = true);
      exit();
      */
      $activity = Activity::with('communities','volunteers')->orderBy('id', 'ASC')->paginate(5);
			// dd($activity);
      return view('activities.index')->with('activities', $activity);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
      //
      return view('activities.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(ActivitiesRequest $request)
  {
      //
      // dd($request->all());

      $activity = new Activity($request->all());
      $response = $activity->save();
      return redirect()->action('ActivitiesController@index');;

  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
      //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
			$activity = Activity::find($id);
      $activity_communities = Activity::find($id)->communities;
			// dd($activity_communities);
			$communities = Community::get();
			$context = [
				'activity'=>$activity,
				'activity_communities'=>$activity_communities,
				'communities'=>$communities
			];

      return view('activities.edit')->with($context);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
      // dd(Community::find($request->communities));
      $activity = Activity::find($id);
      //$activity->fill($request->all());    Hace lo mismo que los 3 de abajo
      $activity->name = $request->name;
      $activity->description = $request->description;
			$activity->save();

			$activity->communities()->detach();
			$communities = Community::find($request->communities);

			if($communities){
				$activity->communities()->saveMany($communities);
			}

      return redirect()->route('activities.index');

  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
      //
      $activity = Activity::find($id);
      $activity->delete();
      return redirect()->route('activities.index');
  }
}

resources/views/activities/create.blade.php
@extends('layouts.app')

@section('title','Activities')

@section('content')
<div class="row justify-content-center">
	<div class="col-4 mt-3">
			<h1>Add Activity</h1>

		 @if(count($errors) > 0)
		   <ul>
		   @foreach($errors->all() as $error)
		     <li>{{$error}}</li>
		   @endforeach
		 </ul>
		 @endif

		 <form class="" action="{{ action('ActivitiesController@store') }}" method="POST">
		 	<input type="hidden" name="_token" value="{{ csrf_token() }}">
		 	<div class="form-group">
		 		<label for="name">Name</label>
		 		<input
		 			type="text" class="form-control" name="name"
		 			placeholder="Activity Name" required>
		 	</div>
		 	<div class="form-group">
		 		<label for="description">Description</label>
				<textarea
					class="form-control text-justify" name="description"
					rows="3" placeholder="Description" required></textarea>
		 	</div>
		 	<div class="form-group">
		 		<button type="submit" class="btn btn-primary">Add</button>
		 	</div>
		 </form>

	</div>
</div>
@endsection

resources/views/activities/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Activity ' . $activity->name)

@section('content')
<div class="row justify-content-center">
	<div class="col-4 mt-3">
		<form class="" action="{{ route('activities.update', $activity->id) }}" method="POST">
			<input type="hidden" name="_method" value="PUT">
			<input type="hidden" name="_token" value="{{ csrf_token() }}">
			<div class="form-group">
				<label for="name">Name</label>
				<input
				type="text" class="form-control" name="name"
				value="{{ $activity->name }}" placeholder="Activity Name" required>
			</div>
			<div class="form-group">
				<label for="description">Description</label>
				<textarea
					class="form-control text-justify" name="description"
					rows="3" placeholder="Description" required
					>{{ $activity->description }}</textarea>
				<!-- <input
				type="text" class="form-control" name="description"
				value="{{ $activity->description }}" placeholder="Description" required> -->
			</div>

			<div class="form-group">
				<label for="communty_id">Assign Communities</label>
				<br>
				<select class="custom-select" multiple="multiple" name="communities[]" style="width: 50%;height: 4%;">
					@foreach ($communities as $community)
					<option value="{{ $community->id }}">{{ $community->name }}</option>
					@endforeach
				</select>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary">Submit</button>
			</div>
		</form>
	</div>
</div>

@endsection

resources/views/activities/index.blade.php
@extends('layouts.app')

@section('title','Activities')

@section('content')
  <h1>Activities</h1>
  <table class="table table-striped">
      <thead>
      	 <th></th>
      	 <th>Name</th>
				 <th>Description</th>
				 <th>Communities</th>
         <th>Volunteers</th>
         <th></th>
      	 <th></th>
      </thead>
      <tbody>
        @foreach($activities as $activity)
           <tr>
               <td></td>
               <td>{{ $activity->name }}</td>
							 <td>{{ $activity->description }}</td>
               <td>
									@foreach ($activity->communities as $community)
										<span > {{ $community->name }} </span>
										<br>
									@endforeach
							 </td>
							 <td>
								 @foreach ($activity->volunteers as $volunteer)
									 <span > {{ $volunteer->firstName }} {{ $volunteer->lastName }}</span>
									 <br>
								 @endforeach
							</td>
               <td>
                 <a
								 	href="{{ route('activities.edit', $activity->id) }}"
									class="btn btn-warning">
									<span>Edit</span>
								</a>
               </td>
               <td>
                 <a
								 	href="{{ route('activities.destroy', $activity->id) }}"
									onclick="return confirm('are you sure?')"
									class="btn btn-danger">
                   <span>Delete</span>
                 </a>
               </td>
           </tr>
        @endforeach
      </tbody>
  </table>
  {!! $activities->links() !!}
@endsection